src/main/java/odyssey/backend/roadmap/controller/RoadmapController.java
src/main/java/odyssey/backend/roadmap/dto/RoadmapCountResponse.java
src/main/java/odyssey/backend/roadmap/service/RoadmapService.java
src/test/java/odyssey/backend/roadmap/RoadmapControllerTest.java

close #8 
<br>
로드맵 총 갯수의 반환타입 변경
> 
<br>
ResponseEntity에서 DTO로 반환타입을 변경하여 유지보수가 쉽게 변경하였습니다.
- 
<br>
<br>

[개선] 로드맵 개수 반환 dto로

---

src/main/java/odyssey/backend/global/exception/RoadmapNotFoundException.java
src/main/java/odyssey/backend/node/service/NodeService.java
src/main/java/odyssey/backend/roadmap/service/RoadmapService.java

close #10 
<br>
RoadmapNotFoundException 작성
> 
<br>
- RoadmapNotFoundException 클래스를 작성하였습니다.
- 서비스로직에 반영하였습니다.
<br>
<br>

[개선] RoadmapNotFoundException 작성

---

src/main/java/odyssey/backend/global/exception/NodeNotFoundException.java
src/main/java/odyssey/backend/global/exception/RoadmapNotFoundException.java
src/main/java/odyssey/backend/node/service/NodeService.java
src/main/java/odyssey/backend/roadmap/service/RoadmapService.java

close #14 
<br>
노드 조회 실패 예외처리를 작성하였습니다.
> 
<br>
- NodeNotFoundException 클래스를 작성하였습니다.
- 서비스로직에 적용시켰습니다.
<br>
<br>

[개선] NodeNotFoundException 작성

---

src/main/java/odyssey/backend/global/exception/ExceptionResponse.java
src/main/java/odyssey/backend/global/exception/GlobalExceptionHandler.java

close #17 
<br>
예외처리 핸들러 추가
> 
<br>
- RoadmapNotFoundException의 예외 핸들러를 작성하였습니다.
- NodeNotFoundException의 예외 핸들러를 작성하였습니다.
<br>
<br>

[개선] 예외처리 핸들러

---

src/main/java/odyssey/backend/image/domain/ImageRepository.java
src/main/java/odyssey/backend/image/service/ImageService.java
src/main/java/odyssey/backend/roadmap/service/RoadmapService.java

close #24 
<br>
> 반복되는 메서드를 제거하였습니다.
<br>
- ImageService에 public메서드를 작성하였습니다.
- RoadmapService에서 해당 메서드로 이미지를 매칭하게 하였습니다. 
<br>
<br>

[개선] 반복 코드 제거

---

src/main/java/odyssey/backend/node/service/NodeService.java

NodeService 의 반복되는 메서드를 별도의 private 메서드로 분리
close #22 
<br>
> 반복되는 메서드를 하나의 private 메서드로 바꾸었습니다.
<br>
- findById메서드를 하나의 private메서드로 분리하였습니다.
<br>
<br>

[개선] 중복 코드 제거

---

src/main/java/odyssey/backend/node/domain/NodeRepository.java
src/main/java/odyssey/backend/node/service/NodeService.java

close #21 
<br>
> 노드가 없을  경우 빈 리스트를 반환하도록 했습니다.
<br>
- NodeRepository의 메서드에서 Optional을 제거하였습니다
- NodeService의 메서드에서 리스트가 빌 경우 예외처리를 하지 않고 빈 리스트를 반환하도록 하였습니다.
<br>
<br>

[개선] UX 개선

---

src/main/java/odyssey/backend/node/domain/Node.java
src/main/java/odyssey/backend/node/service/NodeService.java
src/main/java/odyssey/backend/roadmap/domain/Roadmap.java
src/main/java/odyssey/backend/roadmap/service/RoadmapService.java

close #20
<br>
> 로드맵과 노드의 업데이트 파라미터를 변경하였습니다.
<br>
- 리퀘스트 객체를 받고 있던 update 메서드를 리퀘스트의 파라미터를 변수로 받도록 변경하였습니다.
<br>
<br>

[개선] 업데이트 로직 변경

---

src/main/java/odyssey/backend/node/service/NodeService.java

최상위 부모노드만 응답되도록 stream 메서드에 filter 를 적용시켜 최상위 부모노드만 출력되도록 수정
close #34 
<br>
> 자식노드가 최상위로 출력되지않게 수정했습니다.
<br>
- nodefilter에 filter를 적용시켜 부모노드만 응답하도록 수정하였습니다.
<br>
<br>

[버그] 잘못된 노드 응답 개선

---

src/main/java/odyssey/backend/node/service/NodeService.java
src/main/java/odyssey/backend/roadmap/domain/Roadmap.java
src/main/java/odyssey/backend/roadmap/service/RoadmapService.java

close #33 
<br>
> 수정시간 업데이트 메서드를 update 에서 분리하였습니다.
<br>
- RoadmapService에 수정된 메서드를 반영하였습니다.
-
<br>
<br>

[개선] 수정시간 업데이트 메서드 분리

---

build.gradle

기능별 정리
close #40
<br>
> 의존성 정리하였습니다.
<br>
- 의존성 정리하였습니다.
<br>
<br>

[개선] build.grade 구분

---

src/main/java/odyssey/backend/global/config/WebConfig.java
src/main/java/odyssey/backend/global/exception/ExceptionCode.java
src/main/java/odyssey/backend/global/exception/ExecptionCode.java
src/main/java/odyssey/backend/global/exception/GlobalExceptionHandler.java

close #41 
<br>
> 예외를 enum화 시켰습니다.
<br>
- enum 클래스를 생성하였습니다
- handler 클래스에 반영시켰습니다.
<br>
<br>

[개선] Exception enum화

---

build.gradle

버전 수정
close #39 
<br>
> 스웨거 문서 작성하였습니다
<br>
- 스웨거 문서를 작성하였습니다.
- 스프링 버전과 swagger 버전을 맞추었습니다.
<br>
<br>

[새기능] 스웨거 작성

---

src/main/java/odyssey/backend/global/exception/ExceptionCode.java
src/main/java/odyssey/backend/global/exception/GlobalExceptionHandler.java

잘못된 요청 핸들러 작성
close #45 
<br>
> 예외처리 작성 처리
<br>
- 핸들러 수정
<br>
<br>

[개선] 잘못된 요청 예외처리 적용

---

src/main/java/odyssey/backend/directory/service/DirectoryService.java
src/main/java/odyssey/backend/global/exception/DirectoryNotFoundException.java
src/main/java/odyssey/backend/global/exception/ExceptionCode.java
src/main/java/odyssey/backend/global/exception/GlobalExceptionHandler.java

close #50 
<br>
> DirectoryNotFoundException 작성하였습니다
<br>
- DirectoryNotFoundException 작성 및 서비스와 핸들러에 적용시켰ㅅ븐디ㅏ.
<br>
<br>

[개선] DirectoryNotFoundException 작성

---

src/main/java/odyssey/backend/global/config/WebConfig.java

close #59
<br>
> 배포 후 프론트엔드와의 연동을 위해서 CORS 세팅을 추가했습니다.
<br>
- 배포 후 프론트엔드와의 연동을 위해서 CORS 세팅을 추가
<br>
<br>

[새기능] CORS 추가

---

build.gradle
src/main/java/odyssey/backend/directory/exception/DirectoryNotFoundException.java
src/main/java/odyssey/backend/directory/service/DirectoryService.java
src/main/java/odyssey/backend/global/exception/ExceptionCode.java
src/main/java/odyssey/backend/global/exception/GlobalExceptionHandler.java
src/main/java/odyssey/backend/image/exception/ImageSaveException.java
src/main/java/odyssey/backend/image/exception/InvalidImageFormatException.java
src/main/java/odyssey/backend/image/service/ImageService.java
src/main/java/odyssey/backend/node/exception/NodeNotFoundException.java
src/main/java/odyssey/backend/node/service/NodeService.java
src/main/java/odyssey/backend/roadmap/exception/RoadmapNotFoundException.java
src/main/java/odyssey/backend/roadmap/service/RoadmapService.java

close #60 
<br>
> 예외처리들의 위치를 변경했습니다.
<br>
- 예최러리 클래스들의 디렉토리 위치를 변경하였습니다.
- 이미지 관련 예외처리들을 만들었습니다.
- build.gradle의 시큐리티를 잠시 비활성화했습니다.
<br>
<br>

[개선] 익셉션 파일 위치 변경

---

src/main/java/odyssey/backend/global/config/WebConfig.java

프론트 배포 주소 CORS에 등록
close #67
<br>
> 프론트 배포 주소 CORS에 등록
<br>
- 프론트 배포 주소를 CORS에 추가 등록
<br>
<br>

[개선] 프론트 배포 주소 CORS에 등록

---

src/main/java/odyssey/backend/global/config/WebConfig.java

잘못 작성된 CORS 설정 수정
close #69 
<br>
> 잘못 작성된 CORS 설정 수정
<br>
- CORS 설정에 잘못 추가된 슬래시 삭제
<br>
<br>

[개선] CORS 수정

---

src/main/java/odyssey/backend/directory/controller/DirectoryController.java
src/main/java/odyssey/backend/node/controller/NodeController.java
src/main/java/odyssey/backend/roadmap/controller/RoadmapController.java

close #75 
<br>
> API 별 HttpStatus를 작성하였습니다.
<br>
- RoadmapController의 API들에 HttpStatus를 작성하였습니다.
- NodeController의 API들에 HttpStatus를 작성하였습니다.
- DirectoryController의 API들에 HttpStatus를 작성하였습니다.
<br>
<br>

[개선] RespnoseStatus 작성

---

src/main/java/odyssey/backend/image/service/ImageService.java
src/main/java/odyssey/backend/roadmap/service/RoadmapService.java

close #77 
<br>
> 서버에서도 이미지가 삭제되도록 수정하였습니다.
<br>
- db의 url만 삭제되는 것이 아닌 서버에 저장되어 있는 이미지 파일들도 삭제되도록 메서드를 작성하여 서비스에 적용시켰습니다.
<br>
<br>

[개선] 이미지 삭제

---

src/main/java/odyssey/backend/global/config/WebConfig.java

CORS에서 OriginPatterns가 반복되면 덮어쓰기 된다는 점을 확인 후 수정
close #86
<br>
> CORS 덮어쓰기 에러 수정
<br>
- OriginPatterns가 반복되면 덮어쓰기 된다는 점을 확인 후 수정
<br>
<br>

[개선] : CORS 덮어쓰기 오류 수정

---

src/main/java/odyssey/backend/directory/dto/DirectoryRequest.java

message 위치가 잘못되어있던 것을 수정하였습니다.
close #90 
<br>
> message의 위치를 수정하였습니다.
<br>
- message의 위치가 잘못되어있어 수정하였습니다.
<br>
<br>

[개선] directory 도메인의 DTO 검증 메시지 

---

src/main/java/odyssey/backend/roadmap/controller/RoadmapController.java
src/main/java/odyssey/backend/roadmap/service/RoadmapFacade.java
src/main/java/odyssey/backend/roadmap/service/RoadmapService.java

close #98 
<br>
> Facade로 분리
<br>
- Facade로 분리하였습니다.
<br>
<br>

[개선] Facade 패턴 사용

---

build.gradle
src/main/java/odyssey/backend/directory/domain/Directory.java
src/main/java/odyssey/backend/directory/service/DirectoryService.java
src/main/java/odyssey/backend/node/domain/Node.java
src/main/java/odyssey/backend/node/service/NodeService.java
src/main/java/odyssey/backend/roadmap/domain/Roadmap.java
src/main/java/odyssey/backend/roadmap/service/RoadmapFacade.java
src/test/java/odyssey/backend/Node/NodeControllerTest.java
src/test/java/odyssey/backend/directory/DirectoryControllerTest.java
src/test/java/odyssey/backend/global/ControllerTest.java
src/test/java/odyssey/backend/roadmap/RoadmapControllerTest.java

close #107 
<br>
> 정적팩토리 메서드명 변경
<br>
- 정적팩토리메서드들의 메서드명을 변경하였습니다.
<br>
<br>

[개선] 정적팩토리 메서드 명 변경

---

src/main/java/odyssey/backend/User.java
src/main/java/odyssey/backend/user/Repository/UserRepository.java
src/main/java/odyssey/backend/user/controller/SignUpController.java
src/main/java/odyssey/backend/user/domain/User.java
src/main/java/odyssey/backend/user/dto/request/SignUpRequest.java
src/main/java/odyssey/backend/user/dto/response/SignUpResponse.java
src/main/java/odyssey/backend/user/service/SignUpService.java
src/test/java/odyssey/backend/global/ControllerTest.java
src/test/java/odyssey/backend/user/SingUpControllerTest.java

close #81 
<br>
> 유저 엔티티 작성
> 회원가입 기능 구현
<br>
- 유저 엔티티를 작성하였습니다
- 회원가입 기능과 컨트롤러를 구현하였습니다.
- 테스트 코드를 작성하였습니다ㅏ.
<br>
<br>

[새기능] 유저 엔티티 작성

---

build.gradle
src/main/java/odyssey/backend/global/config/SecurityConfig.java

close #79 
<br>
> 시큐리티 활성화
<br>
- 시큐리티 의존성을 다시 활성화하였습니다.
- SecurityConfig를 작성하였습니다.
<br>
<br>

[개선] 시큐리티 활성화

---

docker-compose.local.yml

close #115 
<br>
> 로컬용 도케 명령어를 세팅했스빈다
<br>
- 로컬용 도케 명령어를 세팅했스빈다
<br>
<br>

[새기능] 로컬 도커 세팅 

---

src/docs/asciidoc/apply.adoc
src/docs/asciidoc/index.adoc
src/docs/asciidoc/team.adoc
src/docs/asciidoc/user.adoc
src/main/java/odyssey/backend/team/controller/TeamApplyController.java
src/main/java/odyssey/backend/team/controller/TeamController.java
src/main/java/odyssey/backend/team/domain/Team.java
src/main/java/odyssey/backend/team/domain/TeamApply.java
src/main/java/odyssey/backend/team/domain/TeamApplyRepository.java
src/main/java/odyssey/backend/team/domain/TeamRepository.java
src/main/java/odyssey/backend/team/dto/request/TeamRequest.java
src/main/java/odyssey/backend/team/dto/response/ApplyResponse.java
src/main/java/odyssey/backend/team/dto/response/TeamResponse.java
src/main/java/odyssey/backend/team/service/TeamApplyService.java
src/main/java/odyssey/backend/team/service/TeamService.java
src/main/java/odyssey/backend/user/domain/User.java
src/test/java/odyssey/backend/global/ControllerTest.java
src/test/java/odyssey/backend/team/TeamApplyControllerTest.java
src/test/java/odyssey/backend/team/TeamControllerTest.java

close #120 
<br>
> 팀기능추가
<br>
- 팀긴으추가
<br>
<br>

[새기능] 팀 기능 추가

---

src/main/java/odyssey/backend/team/domain/Team.java
src/main/java/odyssey/backend/team/domain/TeamRepository.java
src/main/java/odyssey/backend/team/dto/response/TeamResponse.java
src/main/java/odyssey/backend/team/service/TeamService.java

close #130 
<br>
> ㅇㅇ
<br>
- 작업함
<br>
<br>

[개선] 유저 멤버에 팀장 안들어가 ㅁ

---

src/main/java/odyssey/backend/roadmap/domain/Roadmap.java

close #131 
<br>
> ㅇㅇ
<br>
- ㅇㅇ
<br>
<br>

[개선] 업데이트 시 수정시간 반영 안됨

---

src/main/java/odyssey/backend/domain/auth/exception/InvalidPasswordException.java
src/main/java/odyssey/backend/domain/auth/exception/UserNotFoundException.java
src/main/java/odyssey/backend/domain/auth/exception/error/UserExceptionProperty.java
src/main/java/odyssey/backend/domain/directory/exception/DirectoryNotFoundException.java
src/main/java/odyssey/backend/domain/directory/exception/error/DirectoryExceptionProperty.java
src/main/java/odyssey/backend/domain/node/exception/NodeNotFoundException.java
src/main/java/odyssey/backend/domain/node/exception/error/NodeExceptionProperty.java
src/main/java/odyssey/backend/domain/roadmap/exception/RoadmapNotFoundException.java
src/main/java/odyssey/backend/domain/roadmap/exception/error/RoadmapExceptionProperty.java
src/main/java/odyssey/backend/shared/exception/ErrorProperty.java
src/main/java/odyssey/backend/shared/exception/GlobalErrorProperty.java
src/main/java/odyssey/backend/shared/exception/GlobalExceptionHandler.java
src/main/java/odyssey/backend/shared/response/ErrorResponse.java

close #138 
<br>
> 전역 예외처리 추가
<br>
- 전역 예외처리 추가
<br>
<br>

[새기능] 전역 익셉션 처리

---

src/main/java/odyssey/backend/application/roadmap/RoadmapFacade.java
src/main/java/odyssey/backend/application/team/TeamService.java

close #143 
<br>
> 로드맵 생성 때 팀아이디로 팀을 조회 한뒤 없으면 예외 반환
<br>
- ㅇㅇ
<br>
<br>

[개선] 로드맵 생성시 팀 조회

---

src/main/java/odyssey/backend/presentation/auth/AuthController.java
src/main/java/odyssey/backend/presentation/directory/DirectoryController.java
src/main/java/odyssey/backend/presentation/roadmap/RoadmapController.java
src/main/java/odyssey/backend/presentation/team/TeamApplyController.java
src/main/java/odyssey/backend/presentation/team/TeamController.java
src/test/java/odyssey/backend/directory/DirectoryControllerTest.java
src/test/java/odyssey/backend/roadmap/RoadmapControllerTest.java
src/test/java/odyssey/backend/team/TeamApplyControllerTest.java
src/test/java/odyssey/backend/user/AuthControllerTest.java

close #141
<br>
> 엔드포인트 restful하게 변경
<br>
- 
<br>
<br>

[개선] 컨트롤러 개선

---

src/main/java/odyssey/backend/domain/team/exception/TeamNotFoundException.java
src/main/java/odyssey/backend/domain/team/exception/error/TeamExceptionProperty.java

close #145 
<br>
> d
<br>
- d
<br>
<br>

[개선] 예외처리 경우 추가

---

src/main/java/odyssey/backend/domain/node/Node.java
src/main/java/odyssey/backend/domain/node/NodeType.java
src/main/java/odyssey/backend/domain/roadmap/Roadmap.java
src/main/java/odyssey/backend/presentation/node/dto/response/NodeResponse.java
src/test/java/odyssey/backend/node/NodeControllerTest.java

close #160
<br>
> 이넘 수정
<br>
- 전부 대문자로
<br>
<br>

[개선] enum 수정

---

src/main/resources/application.yml

yml .env 설정 변경
close #173 
<br>
> 이미 env 설정이 존재하길래 수정함
<br>
- yml .env 설정 수정
<br>
<br>

[새기능] .env를 읽어내기 위한 dotenv 추가

---

src/main/java/odyssey/backend/application/auth/LoginService.java
src/main/java/odyssey/backend/infrastructure/cookie/CookieUtil.java
src/main/java/odyssey/backend/infrastructure/jwt/JWTAuthenticationFilter.java
src/main/java/odyssey/backend/presentation/auth/AuthController.java
src/test/java/odyssey/backend/user/AuthControllerTest.java

close #176 
<br>
> 쿠키에 토큰을 담도록 함
<br>
- 필터 수정
- 쿠키에 담도록 수정
<br>
<br>

[개선] 토큰 저장 방식 변경
